// MOVIES requests

# @hostname = api.example.com
# @port = 8080
# @host = {{hostname}}:{{port}}
# GET https://{{host}}/authors/{{name}} HTTP/1.1

@host = http://localhost:5000

GET {{host}}

###

GET {{host}}/api/movies/6a298268830303710b892723

###

POST {{host}}/api/movies
Content-Type: application/json

{
    "title": "Up",
    "year": 2009,
    "director": "Almayo Mekonen",
    "rating": 8.3,
    "leadActor": "Almayo Mekonen",
    "duration": 96,
    "genre": ["Kids", "Adventure", "Comedy"],
    "description": "up is a 2009 American computer-animated comedy-drama adventure film produced by Pixar Animation Studios and released by Walt Disney Pictures. Directed by Pete Docter, co-directed by Bob Peterson, and produced by Jonas Rivera, the film features the voices of Edward Asner, Christopher Plummer, Jordan Nagai, Bob Peterson, Delroy Lindo, Jerome Ranft, and Elie Docter. The film follows 78-year-old Carl Fredricksen and an earnest young Wilderness Explorer named Russell as they fly to South America in a house suspended by helium balloons. Along the way, they encounter talking dogs and a giant bird named Kevin."
}

###

PUT {{host}}/api/movies/6a298268830303710b89272a
Content-Type: application/json

{
    
    "year": 2022
  
}

// test id
# PUT {{host}}/api/movies/999
# Content-Type: application/json

# {
#     "title": "Nice Movie",
#     "year": 2026,
#     "director": "Elior Cohen",
#     "rating": 10,
#     "leadActor": "Elior Cohen",
#     "duration": 100,
#     "genre": ["Comedy", "Drama"],
#     "description": "סרטים מגניבים על ידי אליאור כהן"
# }

###
DELETE  {{host}}/api/movies/6a298268830303710b892730


// USERS requests

### 
GET {{host}}/api/users

###
GET {{host}}/api/users/6a298268830303710b89273a

### 
GET {{host}}/api/users/999

### 
GET {{host}}/api/users?search=cobb

### 
GET {{host}}/api/users?genre=Sci-Fi

### 
POST {{host}}/api/users/6a298268830303710b89273a

Content-Type: application/json

{
  "username": "Nadav",
  "email": "nadavbm1@Walla.com"
}

### 
POST {{host}}/api/users/6a298268830303710b89273a
Content-Type: application/json

{
  "username": "morpheus",
  "email": "morpheus@zion.org",
  "fullName": "Morpheus",
  "favoriteGenres": ["Sci-Fi", "Action", "Philosophy"]
}

### 
POST {{host}}/api/users
Content-Type: application/json

{
  "username": "incomplete"
}

### -----------------------------------------------------------
POST {{host}}/api/users
Content-Type: application/json

{
  "username": "neo",
  "email": "imposter@matrix.io"
}

### 
GET {{host}}/api/users/1/watchlist

### 
GET {{host}}/api/users/5/watchlist

###
POST {{host}}/api/users/4/watchlist
Content-Type: application/json

{
  "movieId": 2
}

### 
POST {{host}}/api/users/1/watchlist
Content-Type: application/json

{
  "movieId": 1
}

### 
POST {{host}}/api/users/1/watchlist
Content-Type: application/json

{
  "movieId": 999
}

### 
DELETE {{host}}/api/users/1/watchlist/2

### 
POST {{host}}/api/users
Content-Type: application/json

{
  "username": "newbie",
  "email": "newbie@streamflix.com",
  "favoriteGenres": ["Drama"]
}

### 
GET {{host}}/api/users/6

### 
POST {{host}}/api/users/6/watchlist
Content-Type: application/json

{
  "movieId": 1
}

### 
POST {{host}}/api/users/6/watchlist
Content-Type: application/json

{
  "movieId": 3
}

### 
POST {{host}}/api/users/6/watchlist
Content-Type: application/json

{
  "movieId": 5
}

### 
GET {{host}}/api/users/
